---
- name: Install Mariadb
  apt:
    pkg:
      - mariadb-server
      - mariadb-client
      - rsync
    state: latest
    update_cache: yes

- name: modify mariadb conf
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address.*$"
    line: "bind-address = 0.0.0.0"
  register: mariaconf
  
- name: restart mariadb
  systemd:
    name: mariadb.service
    state: restarted
  when: mariaconf.changed