---
- name: Install Keepalived
  apt:
    name: keepalived
    state: latest

- name: Copy keepalived backup conf
  template:
    src: roles/keepalived/templates/keepalived_backup.conf
    dest: /etc/keepalived/keepalived.conf
    
- name: restart keepalived
  systemd:
    name: keepalived.service
    state: restarted
