---
- name: install nfs
  apt:
    name: nfs-kernel-server
    state: latest

- name: create nfs directory
  file:
    path: /srv/nfs
    state: directory
    mode: 0755

- name: configure nfs
  lineinfile:
    path: /etc/exports
    regexp: '^/srv/nfs.*$'
    line: '/srv/nfs 10.200.11.0/24(rw,sync,no_subtree_check,no_root_squash,anonuid=33,anongid=33)'
    state: present

- name: export nfs
  command: exportfs -a
  
- name: check wordpress directory existance
  stat:
    path: /srv/nfs/wordpress
  register: wordpressinstall
  
- name: download wordpress archive
  unarchive:
    src: "https://fr.wordpress.org/latest-fr_FR.tar.gz"
    dest: /srv/nfs
    remote_src: yes
  when: not wordpressinstall.stat.exists
